# DOCS https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
#-------------------------------------------------------------------------------

default: warning

#-MODIFIED SETTINGS-------------------------------------------------------------
blanks-around-headings: { lines_below: 0 } # rule of proximity
ul-style: { style: sublist }
ol-prefix: { style: ordered }
line-length: { tables: false, code_block_line_length: 90 }
no-inline-html: { allowed_elements: [img, details, summary, kbd, a, table, tr, td] }

#-DISABLED----------------------------------------------------------------------
ul-indent: false # not compatible with using tabs
no-hard-tabs: false # taken care of by .editorconfig
blanks-around-lists: false # space waster
first-line-heading: false # ignore-comments for linters can be in the first line
no-emphasis-as-heading: false # for small sections that shouldn't be linked in the ToC
