name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label:
            I have [updated to the latest
            version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this
            workflow.
          required: true
        - label: I have read the documentation of the feature I am having problems with.
          required: true
        - label: I am using Alfred 5.5 (lower versions are not supported).
          required: true
        - label:
            I have updated to the latest version of the Metadata-Extractor and the Advanced URI plugin.
          required: true
        - label:
            If the `o…` main search does not work, I made sure that I haven't changed any of the default
            settings of the Metadata-Extractor. Furthermore, I have tried rerunning `osetup` and it still
            does not work.
          required: true
        - label:
            If notes in general can be found, but recently created or renamed notes cannot, I used the
            `oupdate` command to manually update the metadata.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Which part of the workflow is not working and in what way?
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem.
      placeholder: |
        For example:
        1. Go to…
        2. Use the keyword…
        3. Select…
    validations: { required: true }
  - type: textarea
    id: debugging-log
    attributes:
      label: Debugging Log
      description: >
        You can get a debugging log by opening the workflow in Alfred preferences and pressing `cmd + D`.
        A small window will open up. At the top of the window, change `All Information` to `Core
        Information`. Use the malfunctioning part of the workflow once more, copy the content of  the
        log window, and paste it here.
      render: Text
    validations: { required: true }
  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: Any related workflow configuration you have changed from the default.
    validations: { required: true }
  - type: checkboxes
    id: compatibility-mode
    attributes:
      label: Are you using Alfred in Compatibility Mode?
      description: Alfred Appearance settings > Options > Focusing
      options:
        - label: "I am using Compatibility Mode."
          required: false
  - type: textarea
    id: version-info
    attributes:
      label: "Version & System Information"
      description: >
        Please run the command `oinfo` in Alfred. It will copy various version information into your
        clipboard. Paste the result here. (If the command `oinfo` itself also does not work, please state
        so and follow [the instructions
        here.](https://github.com/chrisgrieser/shimmering-obsidian/issues/98#issuecomment-1247370074))
      render: Text
    validations: { required: true }
