name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: textarea
    id: debugging-log
    attributes:
      label: Debugging Log
      description: "You can get a debugging log by opening the workflow in Alfred preferences and pressing `cmd + D`. A small window will open up which will log everything happening during the execution of the Workflow. Use the malfunctioning part of the workflow once more, copy the content of the log window, and paste it here. If the debugging log is long, please attach it as file instead of pasting everything in here."
      render: Text
      placeholder: 'If the log is long, you can truncate the realy long `Shimmering Obsidian[Script Filter]` line.'
    validations:
      required: true
  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: "Attach your workflow configuration file `prefs.plist`. You can find it by right-clicking the workflow in the Alfred settings, and then opening it in Finder."
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: Version & System Information
      description: "Please run the command `oinfo` in Alfred. It will copy various version information into your clipboard. Paste the result here."
      render: Text
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
          required: true
        - label: I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
          required: true
        - label: If the `o...` main search does not work, I have tried rerunning `osetup` and it still does not work.
          required: true
        - label: If I updated from version 2.27.x to 2.28+, I have properly checked out the new information in the workflow configuration and also tried restarting Alfred.
          required: true
