name: Documentation Changes
description: Report errors or suggest additions
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: change-request
    attributes:
      label: Change Requested
      description: Describe what should be added or fixed.
    validations:
      required: true
  - type: input
    id: link-to-docs
    attributes:
      label: Link to the relevant section of the documentation
      placeholder: "https://github.com/chrisgrieser/shimmering-obsidian/blob/main/documentation/..."
    validations:
      required: true
