name: Feature request
description: Suggest an idea
title: "Feature Request: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-requested
    attributes:
      label: Feature Requested
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain the request.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The feature would be useful to more users than just me.
          required: true
        - label: I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
          required: true
        - label: 'Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).'
          required: true
        - label: "If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why."
          required: true
