name: Feature request
description: Suggest an idea
title: "Feature Request: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The feature would be useful to more users than just me.
          required: true
        - label: I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
          required: true
        - label: 'Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).'
          required: true
        - label: "If you are looking for a way to trigger a specific Obsidian command from outside Obsidian, [see this comment explaining how you can easily create such a workflow yourself.](https://github.com/chrisgrieser/shimmering-obsidian/issues/172#issuecomment-2066890678)"
          required: true
  - type: textarea
    id: feature-requested
    attributes:
      label: Feature Requested
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: Especially when there is already an Obsidian plugin doing that, please explain why it makes sense to have such a feature available via Alfred.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain the request.
