name: Update Documentation Search Index

on:
  # once a month (14:14 at the 14th of the month)
  schedule:
    - cron: "14 14 14 * *"

  # allow triggering manually
  workflow_dispatch:

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: update documentation search index
        run: |
          for i in {1..5}; do
            echo "Attempt #$i"
            node ./.github/doc-search-cache/re-index-documentation.mjs \
              > ./.github/doc-search-cache/cache.json && exit 0
            sleep 30
          done
          echo "Multiple attempts to re-index the Obsidian docs failed. Aborting."
          exit 1

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Updated documentation index"
          branch: ${{ github.head_ref }}
